### ISSUE TITLE
Inconsistent setting of page-title in browser to title of the model

### ISSUE THREAD

**Issue by tiku01** [tiku01/oryx-editor#525]
When saving a model, the title is displayed as the page-title in the browser as well. When opening an already saved model, this does not happen.

Steps to reproduce:
1) Create a new model (opens the editor in a new tab). At this point the window has the title "Oryx-Editor - Oryx".
2) Save the model by pressing the disc-icon on the very left of the top-bar. 
3) A window pops up and asks for a name as well as a description for the new model. When pressing the "Save" button in that dialogue, the window-title becomes the title of the model as it was just entered into the dialogue.
4) Close the new model you just saved and return to main-page of Oryx (repository).
5) Open the new model by clicking on it. A new tab gets opened with the model loaded into the editor. The title is "Oryx-Editor - Oryx" again.

Should-Be: Set the page-title to become the title of the model after loading (in the same way as it is set within saving the model.

**Comment by gautamsawala** [comment]
The function initializing the title, always set the title to "Oryx-Editor - Oryx"
Changed the function to get the model name, and set the same in the function.
Fixed the problem with #529

**Comment by tiku01** [comment]
It seems this is not fixed, yet. At least on iwioryx the title still get displayed only if saving the model for the first time ....

**Comment by gautamsawala** [comment]
Tried fixing it, please merge the commit #535 
Does it fix the problem?

**Comment by tiku01** [comment]
As commented in the commit the change concerned the wave-component, only (I assume) ... So no, it didn't fix the problem ...

**Comment by tiku01** [comment]
Problem why the fix wasn't effective seems to be the deplyoment (need to delete old folders). After doing that: Worked with all models that I tested now.
